# Site settings
title: James M. Lockard
email: maclockard@gmail.com
description: "I am a junior at Rice University studying computer science."
baseurl: "maclockard.github.io"
url: "maclockard.github.io"
github_username:  maclockard

# Build settings
markdown: kramdown
permalink: pretty
